-- ============================================================
--  RAILWAY SYSTEM SEED DATA (100% COMPLETE)
-- ============================================================

-- ── 1. ZONES ────────────────────────────────────────────────
INSERT INTO zones (code, name, headquarters, abbreviation) VALUES
('CR', 'Central Railway', 'Mumbai CST', 'CR'),
('ER', 'Eastern Railway', 'Kolkata', 'ER'),
('ECR', 'East Central Railway', 'Hajipur', 'ECR'),
('ECoR', 'East Coast Railway', 'Bhubaneswar', 'ECoR'),
('NER', 'North Eastern Railway', 'Gorakhpur', 'NER'),
('NFR', 'Northeast Frontier Railway', 'Maligaon', 'NFR'),
('NR', 'Northern Railway', 'New Delhi', 'NR'),
('NCR', 'North Central Railway', 'Prayagraj', 'NCR'),
('NWR', 'North Western Railway', 'Jaipur', 'NWR'),
('SR', 'Southern Railway', 'Chennai', 'SR'),
('SCR', 'South Central Railway', 'Secunderabad', 'SCR'),
('SER', 'South Eastern Railway', 'Kolkata Garden Reach', 'SER'),
('SECR', 'South East Central Railway', 'Bilaspur', 'SECR'),
('WR', 'Western Railway', 'Mumbai Churchgate', 'WR'),
('WCR', 'West Central Railway', 'Jabalpur', 'WCR'),
('SWR', 'South Western Railway', 'Hubballi', 'SWR'),
('KR', 'Konkan Railway', 'Navi Mumbai', 'KR'),
('Metro', 'Kolkata Metro', 'Kolkata', 'METRO');

-- ── 2. STATIONS ─────────────────────────────────────────────
INSERT INTO stations (code, name, state, zone_id, category) VALUES
('NDLS', 'New Delhi', 'Delhi', (SELECT id FROM zones WHERE code='NR'), 'NSG-1'),
('DLI', 'Old Delhi', 'Delhi', (SELECT id FROM zones WHERE code='NR'), 'NSG-1'),
('NZM', 'Hazrat Nizamuddin', 'Delhi', (SELECT id FROM zones WHERE code='NR'), 'NSG-1'),
('CNB', 'Kanpur Central', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='NR'), 'NSG-1'),
('LKO', 'Lucknow', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='NR'), 'NSG-1'),
('AGC', 'Agra Cantonment', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='NR'), 'NSG-2'),
('MTC', 'Mathura Junction', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='NR'), 'NSG-2'),
('AMV', 'Amravati', 'Maharashtra', (SELECT id FROM zones WHERE code='NR'), 'NSG-3'),
('UMB', 'Ambala Cantonment', 'Haryana', (SELECT id FROM zones WHERE code='NR'), 'NSG-2'),
('LDH', 'Ludhiana', 'Punjab', (SELECT id FROM zones WHERE code='NR'), 'NSG-2'),
('ASR', 'Amritsar', 'Punjab', (SELECT id FROM zones WHERE code='NR'), 'NSG-1'),
('CDG', 'Chandigarh', 'Chandigarh', (SELECT id FROM zones WHERE code='NR'), 'NSG-2'),
('HW', 'Haridwar', 'Uttarakhand', (SELECT id FROM zones WHERE code='NR'), 'NSG-2'),
('DDN', 'Dehradun', 'Uttarakhand', (SELECT id FROM zones WHERE code='NR'), 'NSG-2'),
('SRE', 'Saharanpur', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='NR'), 'NSG-3'),
('ALD', 'Prayagraj Junction', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='NCR'), 'NSG-1'),
('AGC2', 'Agra Fort', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='NCR'), 'NSG-2'),
('JHS', 'Jhansi', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='NCR'), 'NSG-2'),
('GWL', 'Gwalior', 'Madhya Pradesh', (SELECT id FROM zones WHERE code='NCR'), 'NSG-2'),
('BINA', 'Bina Junction', 'Madhya Pradesh', (SELECT id FROM zones WHERE code='NCR'), 'NSG-3'),
('BCT', 'Mumbai Central', 'Maharashtra', (SELECT id FROM zones WHERE code='WR'), 'NSG-1'),
('BVI', 'Borivali', 'Maharashtra', (SELECT id FROM zones WHERE code='WR'), 'NSG-2'),
('ST', 'Surat', 'Gujarat', (SELECT id FROM zones WHERE code='WR'), 'NSG-2'),
('BRC', 'Vadodara', 'Gujarat', (SELECT id FROM zones WHERE code='WR'), 'NSG-1'),
('ADI', 'Ahmedabad', 'Gujarat', (SELECT id FROM zones WHERE code='WR'), 'NSG-1'),
('JP', 'Jaipur', 'Rajasthan', (SELECT id FROM zones WHERE code='WR'), 'NSG-1'),
('AII', 'Ajmer', 'Rajasthan', (SELECT id FROM zones WHERE code='WR'), 'NSG-2'),
('JU', 'Jodhpur', 'Rajasthan', (SELECT id FROM zones WHERE code='WR'), 'NSG-2'),
('UDZ', 'Udaipur City', 'Rajasthan', (SELECT id FROM zones WHERE code='WR'), 'NSG-2'),
('BL', 'Anand Junction', 'Gujarat', (SELECT id FROM zones WHERE code='WR'), 'NSG-3'),
('RTM', 'Ratlam', 'Madhya Pradesh', (SELECT id FROM zones WHERE code='WR'), 'NSG-2'),
('KOTA', 'Kota Junction', 'Rajasthan', (SELECT id FROM zones WHERE code='WR'), 'NSG-2'),
('MTJ', 'Mathura Junction', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='WR'), 'NSG-2'),
('CSMT', 'Mumbai CST', 'Maharashtra', (SELECT id FROM zones WHERE code='CR'), 'NSG-1'),
('DD', 'Dadar', 'Maharashtra', (SELECT id FROM zones WHERE code='CR'), 'NSG-1'),
('KYN', 'Kalyan Junction', 'Maharashtra', (SELECT id FROM zones WHERE code='CR'), 'NSG-2'),
('NK', 'Nashik Road', 'Maharashtra', (SELECT id FROM zones WHERE code='CR'), 'NSG-2'),
('PUNE', 'Pune Junction', 'Maharashtra', (SELECT id FROM zones WHERE code='CR'), 'NSG-1'),
('SUR', 'Solapur', 'Maharashtra', (SELECT id FROM zones WHERE code='CR'), 'NSG-2'),
('NGP', 'Nagpur', 'Maharashtra', (SELECT id FROM zones WHERE code='CR'), 'NSG-1'),
('BSL', 'Bhusaval Junction', 'Maharashtra', (SELECT id FROM zones WHERE code='CR'), 'NSG-2'),
('AK', 'Akola', 'Maharashtra', (SELECT id FROM zones WHERE code='CR'), 'NSG-3'),
('AWB', 'Aurangabad', 'Maharashtra', (SELECT id FROM zones WHERE code='CR'), 'NSG-2'),
('DD2', 'Bhigwan', 'Maharashtra', (SELECT id FROM zones WHERE code='CR'), 'NSG-4'),
('MAS', 'Chennai Central', 'Tamil Nadu', (SELECT id FROM zones WHERE code='SR'), 'NSG-1'),
('MS', 'Chennai Egmore', 'Tamil Nadu', (SELECT id FROM zones WHERE code='SR'), 'NSG-1'),
('CBE', 'Coimbatore', 'Tamil Nadu', (SELECT id FROM zones WHERE code='SR'), 'NSG-1'),
('MDU', 'Madurai Junction', 'Tamil Nadu', (SELECT id FROM zones WHERE code='SR'), 'NSG-1'),
('TVC', 'Thiruvananthapuram', 'Kerala', (SELECT id FROM zones WHERE code='SR'), 'NSG-1'),
('ERS', 'Ernakulam Junction', 'Kerala', (SELECT id FROM zones WHERE code='SR'), 'NSG-1'),
('SRR', 'Shoranur Junction', 'Kerala', (SELECT id FROM zones WHERE code='SR'), 'NSG-2'),
('CAN', 'Kannur', 'Kerala', (SELECT id FROM zones WHERE code='SR'), 'NSG-2'),
('SA', 'Salem Junction', 'Tamil Nadu', (SELECT id FROM zones WHERE code='SR'), 'NSG-2'),
('ED', 'Erode Junction', 'Tamil Nadu', (SELECT id FROM zones WHERE code='SR'), 'NSG-2'),
('TJ', 'Thanjavur Junction', 'Tamil Nadu', (SELECT id FROM zones WHERE code='SR'), 'NSG-2'),
('TEN', 'Tirunelveli', 'Tamil Nadu', (SELECT id FROM zones WHERE code='SR'), 'NSG-2'),
('TCN', 'Tiruchchirapalli', 'Tamil Nadu', (SELECT id FROM zones WHERE code='SR'), 'NSG-1'),
('SC', 'Secunderabad', 'Telangana', (SELECT id FROM zones WHERE code='SCR'), 'NSG-1'),
('HYB', 'Hyderabad Deccan', 'Telangana', (SELECT id FROM zones WHERE code='SCR'), 'NSG-1'),
('KCG', 'Kacheguda', 'Telangana', (SELECT id FROM zones WHERE code='SCR'), 'NSG-2'),
('GNT', 'Guntur', 'Andhra Pradesh', (SELECT id FROM zones WHERE code='SCR'), 'NSG-2'),
('BZA', 'Vijayawada', 'Andhra Pradesh', (SELECT id FROM zones WHERE code='SCR'), 'NSG-1'),
('VSKP', 'Visakhapatnam', 'Andhra Pradesh', (SELECT id FROM zones WHERE code='SCR'), 'NSG-1'),
('TPTY', 'Tirupati', 'Andhra Pradesh', (SELECT id FROM zones WHERE code='SCR'), 'NSG-2'),
('NED', 'Nanded', 'Maharashtra', (SELECT id FROM zones WHERE code='SCR'), 'NSG-2'),
('PAU', 'Parbhani', 'Maharashtra', (SELECT id FROM zones WHERE code='SCR'), 'NSG-3'),
('GTL', 'Guntakal Junction', 'Andhra Pradesh', (SELECT id FROM zones WHERE code='SCR'), 'NSG-2'),
('HWH', 'Howrah Junction', 'West Bengal', (SELECT id FROM zones WHERE code='ER'), 'NSG-1'),
('SDAH', 'Sealdah', 'West Bengal', (SELECT id FROM zones WHERE code='ER'), 'NSG-1'),
('BDC', 'Burdwan', 'West Bengal', (SELECT id FROM zones WHERE code='ER'), 'NSG-2'),
('BWN', 'Bardhaman', 'West Bengal', (SELECT id FROM zones WHERE code='ER'), 'NSG-2'),
('NJP', 'New Jalpaiguri', 'West Bengal', (SELECT id FROM zones WHERE code='ER'), 'NSG-2'),
('MFP', 'Muzaffarpur', 'Bihar', (SELECT id FROM zones WHERE code='ER'), 'NSG-2'),
('PNBE', 'Patna Junction', 'Bihar', (SELECT id FROM zones WHERE code='ER'), 'NSG-1'),
('GAYA', 'Gaya Junction', 'Bihar', (SELECT id FROM zones WHERE code='ER'), 'NSG-2'),
('DHN', 'Dhanbad', 'Jharkhand', (SELECT id FROM zones WHERE code='ER'), 'NSG-2'),
('ASN', 'Asansol', 'West Bengal', (SELECT id FROM zones WHERE code='ER'), 'NSG-2'),
('DNR', 'Danapur', 'Bihar', (SELECT id FROM zones WHERE code='ECR'), 'NSG-3'),
('MGS', 'Mughal Sarai', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='ECR'), 'NSG-2'),
('DDU', 'Pandit Deen Dayal Upadhyaya Jn', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='ECR'), 'NSG-2'),
('BSB', 'Varanasi', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='ECR'), 'NSG-1'),
('GKP', 'Gorakhpur', 'Uttar Pradesh', (SELECT id FROM zones WHERE code='ECR'), 'NSG-1'),
('CPR', 'Chhapra', 'Bihar', (SELECT id FROM zones WHERE code='NER'), 'NSG-3'),
('BJU', 'Barauni', 'Bihar', (SELECT id FROM zones WHERE code='NER'), 'NSG-2'),
('GHY', 'Guwahati', 'Assam', (SELECT id FROM zones WHERE code='NFR'), 'NSG-1'),
('DBRG', 'Dibrugarh', 'Assam', (SELECT id FROM zones WHERE code='NFR'), 'NSG-2'),
('LMG', 'Lumding Junction', 'Assam', (SELECT id FROM zones WHERE code='NFR'), 'NSG-2'),
('AGTL', 'Agartala', 'Tripura', (SELECT id FROM zones WHERE code='NFR'), 'NSG-2'),
('KIR', 'Katihar', 'Bihar', (SELECT id FROM zones WHERE code='NFR'), 'NSG-2'),
('SBC', 'Bengaluru City', 'Karnataka', (SELECT id FROM zones WHERE code='SWR'), 'NSG-1'),
('YPR', 'Yesvantpur Junction', 'Karnataka', (SELECT id FROM zones WHERE code='SWR'), 'NSG-2'),
('UBL', 'Hubballi Junction', 'Karnataka', (SELECT id FROM zones WHERE code='SWR'), 'NSG-2'),
('MYS', 'Mysuru Junction', 'Karnataka', (SELECT id FROM zones WHERE code='SWR'), 'NSG-2'),
('BGM', 'Belagavi', 'Karnataka', (SELECT id FROM zones WHERE code='SWR'), 'NSG-2'),
('KGP', 'Kharagpur', 'West Bengal', (SELECT id FROM zones WHERE code='SER'), 'NSG-2'),
('BBS', 'Bhubaneswar', 'Odisha', (SELECT id FROM zones WHERE code='SER'), 'NSG-1'),
('CTC', 'Cuttack', 'Odisha', (SELECT id FROM zones WHERE code='SER'), 'NSG-2'),
('PURI', 'Puri', 'Odisha', (SELECT id FROM zones WHERE code='SER'), 'NSG-2'),
('ROU', 'Rourkela', 'Odisha', (SELECT id FROM zones WHERE code='SER'), 'NSG-2'),
('JSG', 'Jharsuguda', 'Odisha', (SELECT id FROM zones WHERE code='SER'), 'NSG-3'),
('TAT', 'Tatanagar', 'Jharkhand', (SELECT id FROM zones WHERE code='SER'), 'NSG-2'),
('RNC', 'Ranchi', 'Jharkhand', (SELECT id FROM zones WHERE code='SER'), 'NSG-2'),
('BSP', 'Bilaspur Junction', 'Chhattisgarh', (SELECT id FROM zones WHERE code='SECR'), 'NSG-2'),
('R', 'Raipur Junction', 'Chhattisgarh', (SELECT id FROM zones WHERE code='SECR'), 'NSG-1'),
('BPH', 'Balaghat', 'Madhya Pradesh', (SELECT id FROM zones WHERE code='SECR'), 'NSG-3'),
('BKN', 'Bikaner Junction', 'Rajasthan', (SELECT id FROM zones WHERE code='NWR'), 'NSG-2'),
('JU2', 'Jodhpur Junction', 'Rajasthan', (SELECT id FROM zones WHERE code='NWR'), 'NSG-2'),
('AII2', 'Ajmer Junction', 'Rajasthan', (SELECT id FROM zones WHERE code='NWR'), 'NSG-2'),
('JSLM', 'Jaisalmer', 'Rajasthan', (SELECT id FROM zones WHERE code='NWR'), 'NSG-3'),
('JBP', 'Jabalpur', 'Madhya Pradesh', (SELECT id FROM zones WHERE code='WCR'), 'NSG-2'),
('BPL', 'Bhopal Junction', 'Madhya Pradesh', (SELECT id FROM zones WHERE code='WCR'), 'NSG-1'),
('ET', 'Itarsi Junction', 'Madhya Pradesh', (SELECT id FROM zones WHERE code='WCR'), 'NSG-2'),
('BIL', 'Bilaspur Jn (MP)', 'Madhya Pradesh', (SELECT id FROM zones WHERE code='WCR'), 'NSG-3'),
('RN', 'Ratnagiri', 'Maharashtra', (SELECT id FROM zones WHERE code='KR'), 'NSG-3'),
('MAO', 'Madgaon', 'Goa', (SELECT id FROM zones WHERE code='KR'), 'NSG-2'),
('UD', 'Udupi', 'Karnataka', (SELECT id FROM zones WHERE code='KR'), 'NSG-3'),
('MNG', 'Mangaluru Central', 'Karnataka', (SELECT id FROM zones WHERE code='KR'), 'NSG-2'),
('VSKP2', 'Visakhapatnam Port', 'Andhra Pradesh', (SELECT id FROM zones WHERE code='ECoR'), 'NSG-2'),
('VZM', 'Vizianagaram', 'Andhra Pradesh', (SELECT id FROM zones WHERE code='ECoR'), 'NSG-2'),
('SAMB', 'Sambalpur', 'Odisha', (SELECT id FROM zones WHERE code='ECoR'), 'NSG-3');

-- ── 3. TRAINS ───────────────────────────────────────────────
INSERT INTO trains (train_no, name, zone_id, train_type, total_coaches, origin_code, destination_code) VALUES
(12301, 'Howrah Rajdhani Express', (SELECT id FROM zones WHERE code='NR'), 'Rajdhani Express', 22, 'NDLS', 'HWH'),
(12302, 'New Delhi Rajdhani Express', (SELECT id FROM zones WHERE code='NR'), 'Rajdhani Express', 22, 'HWH', 'NDLS'),
(12001, 'Bhopal Shatabdi Express', (SELECT id FROM zones WHERE code='NR'), 'Shatabdi Express', 20, 'NDLS', 'BPL'),
(12013, 'Amritsar Shatabdi Express', (SELECT id FROM zones WHERE code='NR'), 'Shatabdi Express', 20, 'NDLS', 'ASR'),
(12015, 'Ajmer Shatabdi Express', (SELECT id FROM zones WHERE code='NR'), 'Shatabdi Express', 20, 'NDLS', 'AII'),
(12919, 'Malwa Superfast Express', (SELECT id FROM zones WHERE code='NR'), 'Superfast Express', 24, 'NDLS', 'JP'),
(12311, 'Kalka Mail', (SELECT id FROM zones WHERE code='NR'), 'Mail', 20, 'HWH', 'NDLS'),
(12453, 'Ranchi Rajdhani Express', (SELECT id FROM zones WHERE code='NR'), 'Rajdhani Express', 20, 'NDLS', 'RNC'),
(12559, 'Shivganga Express', (SELECT id FROM zones WHERE code='NR'), 'Superfast Express', 24, 'NZM', 'BSB'),
(22409, 'Goa Express', (SELECT id FROM zones WHERE code='NR'), 'Express', 24, 'NDLS', 'MAO'),
(12241, 'Chandigarh Shatabdi Express', (SELECT id FROM zones WHERE code='NR'), 'Shatabdi Express', 18, 'NDLS', 'CDG'),
(12587, 'Gorakhpur Humsafar Express', (SELECT id FROM zones WHERE code='NR'), 'Humsafar Express', 20, 'NDLS', 'GKP'),
(12003, 'Lucknow Mail', (SELECT id FROM zones WHERE code='NR'), 'Mail', 22, 'NDLS', 'LKO'),
(12225, 'Kaifiyat Express', (SELECT id FROM zones WHERE code='NR'), 'Superfast Express', 22, 'NZM', 'ALD'),
(22439, 'New Delhi–Varanasi Vande Bharat', (SELECT id FROM zones WHERE code='NR'), 'Vande Bharat Express', 16, 'NDLS', 'BSB'),
(12951, 'Mumbai Rajdhani Express', (SELECT id FROM zones WHERE code='WR'), 'Rajdhani Express', 22, 'NDLS', 'BCT'),
(12901, 'Gujarat Mail', (SELECT id FROM zones WHERE code='WR'), 'Mail', 24, 'BCT', 'NDLS'),
(12009, 'Shatabdi Express Mumbai–Ahmedabad', (SELECT id FROM zones WHERE code='WR'), 'Shatabdi Express', 20, 'BCT', 'ADI'),
(12925, 'Paschim Express', (SELECT id FROM zones WHERE code='WR'), 'Superfast Express', 24, 'BCT', 'ASR'),
(12479, 'Suryanagri Express', (SELECT id FROM zones WHERE code='WR'), 'Superfast Express', 22, 'BCT', 'JU'),
(12463, 'Mandor Express', (SELECT id FROM zones WHERE code='WR'), 'Express', 22, 'NDLS', 'JU'),
(12915, 'Ashram Express', (SELECT id FROM zones WHERE code='WR'), 'Superfast Express', 24, 'NDLS', 'ADI'),
(12929, 'Paschim Superfast Express', (SELECT id FROM zones WHERE code='WR'), 'Superfast Express', 24, 'BCT', 'AGC'),
(12955, 'Mumbai–Jaipur Superfast Express', (SELECT id FROM zones WHERE code='WR'), 'Superfast Express', 22, 'BCT', 'JP'),
(12217, 'Kerala Sampark Kranti Express', (SELECT id FROM zones WHERE code='WR'), 'Superfast Express', 24, 'NDLS', 'TVC'),
(22945, 'Saurashtra Mail', (SELECT id FROM zones WHERE code='WR'), 'Mail', 22, 'BCT', 'JP'),
(12933, 'Karnavati Express', (SELECT id FROM zones WHERE code='WR'), 'Superfast Express', 22, 'ADI', 'BCT'),
(22951, 'Mumbai–Ahmedabad Tejas Express', (SELECT id FROM zones WHERE code='WR'), 'Tejas Express', 12, 'BCT', 'ADI'),
(12471, 'Swaraj Express', (SELECT id FROM zones WHERE code='WR'), 'Superfast Express', 24, 'ASR', 'JP'),
(14707, 'Ranakpur Express', (SELECT id FROM zones WHERE code='WR'), 'Express', 22, 'JP', 'BCT'),
(12101, 'Jnaneswari Super Deluxe Express', (SELECT id FROM zones WHERE code='CR'), 'Superfast Express', 24, 'HWH', 'PUNE'),
(12025, 'Pune Shatabdi Express', (SELECT id FROM zones WHERE code='CR'), 'Shatabdi Express', 20, 'CSMT', 'PUNE'),
(11001, 'Udyan Express', (SELECT id FROM zones WHERE code='CR'), 'Superfast Express', 24, 'CSMT', 'SBC'),
(12139, 'Sewagram Express', (SELECT id FROM zones WHERE code='CR'), 'Superfast Express', 22, 'CSMT', 'NGP'),
(12109, 'Panchavati Express', (SELECT id FROM zones WHERE code='CR'), 'Superfast Express', 20, 'CSMT', 'NK'),
(12111, 'Amravati Express', (SELECT id FROM zones WHERE code='CR'), 'Superfast Express', 22, 'CSMT', 'AMV'),
(12127, 'Intercity Express Mumbai-Pune', (SELECT id FROM zones WHERE code='CR'), 'Express', 20, 'CSMT', 'PUNE'),
(11003, 'Tutari Express', (SELECT id FROM zones WHERE code='CR'), 'Express', 22, 'BSL', 'PUNE'),
(22105, 'Indrayani Express', (SELECT id FROM zones WHERE code='CR'), 'Express', 20, 'CSMT', 'PUNE'),
(12263, 'Pune–Hazrat Nizamuddin Duronto', (SELECT id FROM zones WHERE code='CR'), 'Duronto Express', 20, 'PUNE', 'NZM'),
(12219, 'Mumbai–Secunderabad Express', (SELECT id FROM zones WHERE code='CR'), 'Superfast Express', 24, 'CSMT', 'SC'),
(11057, 'Amrapali Express', (SELECT id FROM zones WHERE code='CR'), 'Express', 22, 'CSMT', 'GKP'),
(12071, 'Jalna Janshatabdi Express', (SELECT id FROM zones WHERE code='CR'), 'Jan Shatabdi Express', 12, 'CSMT', 'AWB'),
(12701, 'Hussain Sagar Express', (SELECT id FROM zones WHERE code='CR'), 'Express', 24, 'CSMT', 'SC'),
(12621, 'Tamil Nadu Express', (SELECT id FROM zones WHERE code='CR'), 'Superfast Express', 24, 'NZM', 'MAS'),
(12611, 'Chennai Rajdhani Express', (SELECT id FROM zones WHERE code='SR'), 'Rajdhani Express', 22, 'NZM', 'MAS'),
(12163, 'Chennai Egmore–Mumbai CSMT Express', (SELECT id FROM zones WHERE code='SR'), 'Superfast Express', 24, 'MS', 'CSMT'),
(12027, 'Chennai Shatabdi Express', (SELECT id FROM zones WHERE code='SR'), 'Shatabdi Express', 18, 'MAS', 'CBE'),
(12671, 'Nilagiri Express', (SELECT id FROM zones WHERE code='SR'), 'Express', 18, 'MAS', 'CBE'),
(12641, 'Thirukkural Express', (SELECT id FROM zones WHERE code='SR'), 'Superfast Express', 22, 'MAS', 'MDU'),
(12431, 'Thiruvananthapuram Rajdhani', (SELECT id FROM zones WHERE code='SR'), 'Rajdhani Express', 20, 'NZM', 'TVC'),
(16525, 'Island Express', (SELECT id FROM zones WHERE code='SR'), 'Express', 22, 'MAS', 'TVC'),
(12077, 'Jan Shatabdi Coimbatore', (SELECT id FROM zones WHERE code='SR'), 'Jan Shatabdi Express', 12, 'MAS', 'CBE'),
(12623, 'Trivandrum Mail', (SELECT id FROM zones WHERE code='SR'), 'Mail', 22, 'MAS', 'TVC'),
(16381, 'Kanyakumari Express', (SELECT id FROM zones WHERE code='SR'), 'Express', 24, 'MAS', 'TEN'),
(12083, 'Jan Shatabdi MAS-MDU', (SELECT id FROM zones WHERE code='SR'), 'Jan Shatabdi Express', 12, 'MAS', 'MDU'),
(12695, 'Trivandrum Superfast Express', (SELECT id FROM zones WHERE code='SR'), 'Superfast Express', 22, 'MAS', 'TVC'),
(22659, 'Kochuveli Superfast Express', (SELECT id FROM zones WHERE code='SR'), 'Superfast Express', 22, 'NZM', 'ERS'),
(12157, 'Sabari Express', (SELECT id FROM zones WHERE code='SR'), 'Express', 20, 'MAS', 'ERS'),
(12679, 'Coimbatore–Chennai Intercity', (SELECT id FROM zones WHERE code='SR'), 'Superfast Express', 18, 'CBE', 'MAS'),
(12723, 'Telangana Express', (SELECT id FROM zones WHERE code='SCR'), 'Superfast Express', 24, 'NZM', 'HYB'),
(12164, 'Hyderabad–Mumbai Express', (SELECT id FROM zones WHERE code='SCR'), 'Superfast Express', 24, 'HYB', 'CSMT'),
(22693, 'Bangalore Rajdhani Express', (SELECT id FROM zones WHERE code='SCR'), 'Rajdhani Express', 22, 'NZM', 'SBC'),
(12049, 'Gatimaan Express', (SELECT id FROM zones WHERE code='SCR'), 'Superfast Express', 10, 'NDLS', 'AGC'),
(12213, 'Delhi Duronto Express', (SELECT id FROM zones WHERE code='SCR'), 'Duronto Express', 20, 'NDLS', 'SC'),
(17201, 'Golconda Express', (SELECT id FROM zones WHERE code='SCR'), 'Express', 22, 'SC', 'HYB'),
(12735, 'Secunderabad–Tirupati Express', (SELECT id FROM zones WHERE code='SCR'), 'Superfast Express', 20, 'SC', 'TPTY'),
(17230, 'Sabari Express (SCR)', (SELECT id FROM zones WHERE code='SCR'), 'Express', 22, 'SC', 'TPTY'),
(12513, 'Secunderabad Duronto Express', (SELECT id FROM zones WHERE code='SCR'), 'Duronto Express', 20, 'SC', 'GKP'),
(22416, 'Andhra Pradesh Sampark Kranti', (SELECT id FROM zones WHERE code='SCR'), 'Superfast Express', 22, 'NDLS', 'VSKP'),
(12707, 'Andhra Pradesh Express', (SELECT id FROM zones WHERE code='SCR'), 'Superfast Express', 24, 'NZM', 'BZA'),
(17488, 'Tirumala Express', (SELECT id FROM zones WHERE code='SCR'), 'Express', 22, 'SC', 'TPTY'),
(22694, 'Rajdhani Bangalore–Hazrat Nzm', (SELECT id FROM zones WHERE code='SCR'), 'Rajdhani Express', 22, 'SBC', 'NZM'),
(11019, 'Konark Express', (SELECT id FROM zones WHERE code='SCR'), 'Express', 24, 'CSMT', 'BBS'),
(12740, 'Visakhapatnam Vande Bharat', (SELECT id FROM zones WHERE code='SCR'), 'Vande Bharat Express', 16, 'SC', 'VSKP'),
(12303, 'Poorva Express', (SELECT id FROM zones WHERE code='ER'), 'Superfast Express', 24, 'HWH', 'NZM'),
(12312, 'Kalka Mail (ER)', (SELECT id FROM zones WHERE code='ER'), 'Mail', 22, 'HWH', 'NDLS'),
(12314, 'New Farakka Express', (SELECT id FROM zones WHERE code='ER'), 'Superfast Express', 22, 'NZM', 'SDAH'),
(12316, 'Annanya Express', (SELECT id FROM zones WHERE code='ER'), 'Superfast Express', 22, 'NDLS', 'SDAH'),
(12307, 'Howrah Jodhpur Express', (SELECT id FROM zones WHERE code='ER'), 'Superfast Express', 24, 'HWH', 'JU'),
(13003, 'Rupasi Bangla Express', (SELECT id FROM zones WHERE code='ER'), 'Express', 22, 'HWH', 'AGTL'),
(13121, 'Ganga Sagar Express', (SELECT id FROM zones WHERE code='ER'), 'Express', 22, 'HWH', 'PNBE'),
(13043, 'Rarh Express', (SELECT id FROM zones WHERE code='ER'), 'Express', 20, 'HWH', 'PNBE'),
(12347, 'Rourkela Rajyarani Express', (SELECT id FROM zones WHERE code='ER'), 'Superfast Express', 20, 'HWH', 'ROU'),
(13049, 'Amritsar Express', (SELECT id FROM zones WHERE code='ER'), 'Express', 24, 'HWH', 'ASR'),
(13007, 'Udyan Abha Toofan Express', (SELECT id FROM zones WHERE code='ER'), 'Express', 22, 'HWH', 'NDLS'),
(12023, 'Janshatabdi Howrah-Patna', (SELECT id FROM zones WHERE code='ER'), 'Jan Shatabdi Express', 16, 'HWH', 'PNBE'),
(12369, 'Kumbha Express', (SELECT id FROM zones WHERE code='ER'), 'Superfast Express', 24, 'HWH', 'ALD'),
(13151, 'Kolkata–Jammu Express', (SELECT id FROM zones WHERE code='ER'), 'Express', 24, 'SDAH', 'NDLS'),
(12337, 'Shantiniketan Express', (SELECT id FROM zones WHERE code='ER'), 'Superfast Express', 20, 'HWH', 'BWN'),
(12391, 'Shramjeevi Express', (SELECT id FROM zones WHERE code='ECR'), 'Superfast Express', 22, 'PNBE', 'NDLS'),
(12327, 'Upasana Express', (SELECT id FROM zones WHERE code='ECR'), 'Express', 22, 'HWH', 'BSB'),
(12393, 'Sampoorna Kranti Express', (SELECT id FROM zones WHERE code='ECR'), 'Superfast Express', 24, 'PNBE', 'NDLS'),
(13201, 'Rajendra Nagar Express', (SELECT id FROM zones WHERE code='ECR'), 'Express', 22, 'PNBE', 'NDLS'),
(12565, 'Bihar Sampark Kranti Express', (SELECT id FROM zones WHERE code='ECR'), 'Superfast Express', 22, 'MFP', 'NDLS'),
(22407, 'Vaishali Superfast Express', (SELECT id FROM zones WHERE code='ECR'), 'Superfast Express', 22, 'NDLS', 'BSB'),
(12352, 'Doon Express', (SELECT id FROM zones WHERE code='ECR'), 'Express', 22, 'HWH', 'DDN'),
(15708, 'Amrapali Express (ECR)', (SELECT id FROM zones WHERE code='ECR'), 'Express', 22, 'HWH', 'NJP'),
(12401, 'Nanda Devi Express', (SELECT id FROM zones WHERE code='ECR'), 'Superfast Express', 22, 'HWH', 'DDN'),
(12571, 'Gorakhpur Anand Vihar Express', (SELECT id FROM zones WHERE code='ECR'), 'Superfast Express', 22, 'NDLS', 'GKP'),
(15003, 'Chauri Chaura Express', (SELECT id FROM zones WHERE code='NER'), 'Express', 22, 'NDLS', 'GKP'),
(15017, 'Gorakhpur–Lokmanya Tilak Express', (SELECT id FROM zones WHERE code='NER'), 'Express', 22, 'GKP', 'CSMT'),
(15005, 'Gorakhpur–Anand Vihar Express', (SELECT id FROM zones WHERE code='NER'), 'Express', 22, 'GKP', 'NDLS'),
(12511, 'Rapti Sagar Express', (SELECT id FROM zones WHERE code='NER'), 'Superfast Express', 22, 'GKP', 'TVC'),
(12521, 'Barauni Express', (SELECT id FROM zones WHERE code='NER'), 'Superfast Express', 22, 'GKP', 'ERS'),
(15009, 'Avadh Express', (SELECT id FROM zones WHERE code='NER'), 'Express', 22, 'NDLS', 'LKO'),
(15069, 'Paschim Champaran Humsafar', (SELECT id FROM zones WHERE code='NER'), 'Humsafar Express', 18, 'NDLS', 'CPR'),
(22531, 'Gorakhpur Intercity Express', (SELECT id FROM zones WHERE code='NER'), 'Superfast Express', 18, 'LKO', 'GKP'),
(15707, 'Kisan Express', (SELECT id FROM zones WHERE code='NER'), 'Express', 22, 'GKP', 'NDLS'),
(14217, 'Unchahar Express', (SELECT id FROM zones WHERE code='NER'), 'Express', 22, 'NDLS', 'LKO'),
(12423, 'Dibrugarh Rajdhani Express', (SELECT id FROM zones WHERE code='NFR'), 'Rajdhani Express', 22, 'NDLS', 'DBRG'),
(12507, 'Guwahati Rajdhani Express', (SELECT id FROM zones WHERE code='NFR'), 'Rajdhani Express', 22, 'NDLS', 'GHY'),
(12345, 'Saraighat Express', (SELECT id FROM zones WHERE code='NFR'), 'Superfast Express', 22, 'HWH', 'GHY'),
(15955, 'Brahmaputra Mail', (SELECT id FROM zones WHERE code='NFR'), 'Mail', 20, 'NDLS', 'DBRG'),
(12501, 'Poorvottar Sampark Kranti Express', (SELECT id FROM zones WHERE code='NFR'), 'Superfast Express', 22, 'NZM', 'GHY'),
(15957, 'Kamrup Express', (SELECT id FROM zones WHERE code='NFR'), 'Express', 22, 'HWH', 'DBRG'),
(13281, 'Darjeeling Mail', (SELECT id FROM zones WHERE code='NFR'), 'Mail', 20, 'HWH', 'NJP'),
(12526, 'Agartala Rajdhani Express', (SELECT id FROM zones WHERE code='NFR'), 'Rajdhani Express', 20, 'NDLS', 'AGTL'),
(12235, 'Dibrugarh Intercity Express', (SELECT id FROM zones WHERE code='NFR'), 'Superfast Express', 18, 'DBRG', 'GHY'),
(12505, 'North East Express', (SELECT id FROM zones WHERE code='NFR'), 'Superfast Express', 24, 'NDLS', 'DBRG'),
(22691, 'Rajdhani Express Bangalore', (SELECT id FROM zones WHERE code='SWR'), 'Rajdhani Express', 22, 'NZM', 'SBC'),
(12627, 'Karnataka Express', (SELECT id FROM zones WHERE code='SWR'), 'Superfast Express', 24, 'SBC', 'NDLS'),
(12657, 'Chennai Mail', (SELECT id FROM zones WHERE code='SWR'), 'Mail', 22, 'SBC', 'MAS'),
(16209, 'Mysore Express', (SELECT id FROM zones WHERE code='SWR'), 'Express', 22, 'MAS', 'MYS'),
(12007, 'Mysore Shatabdi Express', (SELECT id FROM zones WHERE code='SWR'), 'Shatabdi Express', 16, 'SBC', 'MYS'),
(12029, 'Bangalore–Chennai Shatabdi', (SELECT id FROM zones WHERE code='SWR'), 'Shatabdi Express', 20, 'SBC', 'MAS'),
(12165, 'Chennai Superfast Express', (SELECT id FROM zones WHERE code='SWR'), 'Superfast Express', 22, 'SBC', 'MAS'),
(16527, 'Yesvantpur–Kannur Express', (SELECT id FROM zones WHERE code='SWR'), 'Express', 22, 'YPR', 'CAN'),
(17321, 'Tungabhadra Express', (SELECT id FROM zones WHERE code='SWR'), 'Express', 22, 'UBL', 'SC'),
(22479, 'Bangalore–Jodhpur Superfast', (SELECT id FROM zones WHERE code='SWR'), 'Superfast Express', 22, 'SBC', 'JU'),
(12841, 'Coromandel Express', (SELECT id FROM zones WHERE code='SER'), 'Superfast Express', 24, 'HWH', 'MAS'),
(12245, 'Yesvantpur Duronto Express', (SELECT id FROM zones WHERE code='SER'), 'Duronto Express', 20, 'HWH', 'YPR'),
(12810, 'Mumbai Mail', (SELECT id FROM zones WHERE code='SER'), 'Mail', 24, 'HWH', 'CSMT'),
(12872, 'Ispat Express', (SELECT id FROM zones WHERE code='SER'), 'Superfast Express', 22, 'HWH', 'ROU'),
(12861, 'Link Howrah Express', (SELECT id FROM zones WHERE code='SER'), 'Express', 22, 'HWH', 'BBS'),
(18045, 'East Coast Express', (SELECT id FROM zones WHERE code='SER'), 'Express', 24, 'HWH', 'BBS'),
(12887, 'Puri–Howrah Express', (SELECT id FROM zones WHERE code='SER'), 'Superfast Express', 22, 'PURI', 'HWH'),
(12895, 'Howrah–Puri Intercity', (SELECT id FROM zones WHERE code='SER'), 'Superfast Express', 18, 'HWH', 'PURI'),
(12881, 'Howrah–Puri Garib Rath Express', (SELECT id FROM zones WHERE code='SER'), 'Garib Rath Express', 18, 'HWH', 'PURI'),
(12509, 'Guwahati Express', (SELECT id FROM zones WHERE code='SER'), 'Superfast Express', 22, 'BBS', 'GHY'),
(12991, 'Udaipur–Jaipur City Express', (SELECT id FROM zones WHERE code='NWR'), 'Superfast Express', 20, 'UDZ', 'JP'),
(12465, 'Ranthambore Express', (SELECT id FROM zones WHERE code='NWR'), 'Superfast Express', 22, 'NDLS', 'KOTA'),
(12967, 'Jaipur Superfast Express', (SELECT id FROM zones WHERE code='NWR'), 'Superfast Express', 22, 'NDLS', 'JP'),
(12969, 'Jaipur–Mumbai Express', (SELECT id FROM zones WHERE code='NWR'), 'Superfast Express', 22, 'JP', 'BCT'),
(14059, 'Pooja Express', (SELECT id FROM zones WHERE code='NWR'), 'Express', 22, 'NDLS', 'BKN'),
(14713, 'Sriganganagar Express', (SELECT id FROM zones WHERE code='NWR'), 'Express', 22, 'NDLS', 'BKN'),
(14060, 'Rangir Express', (SELECT id FROM zones WHERE code='NWR'), 'Express', 22, 'ASR', 'BKN'),
(22977, 'Bikaner Intercity Express', (SELECT id FROM zones WHERE code='NWR'), 'Superfast Express', 18, 'BKN', 'JP'),
(15709, 'Salasar Express', (SELECT id FROM zones WHERE code='NWR'), 'Express', 20, 'JP', 'NDLS'),
(12961, 'Avantika Express', (SELECT id FROM zones WHERE code='NWR'), 'Superfast Express', 22, 'BCT', 'NDLS'),
(12155, 'Shaan-E-Bhopal Express', (SELECT id FROM zones WHERE code='WCR'), 'Superfast Express', 22, 'NDLS', 'BPL'),
(11061, 'Pawan Express', (SELECT id FROM zones WHERE code='WCR'), 'Express', 22, 'CSMT', 'GKP'),
(12189, 'Mahakaushal Express', (SELECT id FROM zones WHERE code='WCR'), 'Superfast Express', 22, 'NDLS', 'JBP'),
(22181, 'Jabalpur Rajdhani Express', (SELECT id FROM zones WHERE code='WCR'), 'Rajdhani Express', 20, 'NDLS', 'JBP'),
(12191, 'Shridham Express', (SELECT id FROM zones WHERE code='WCR'), 'Superfast Express', 22, 'NZM', 'BPL'),
(11079, 'Gwalior Express', (SELECT id FROM zones WHERE code='WCR'), 'Express', 22, 'CSMT', 'GWL'),
(12562, 'Shivganga Express (WCR)', (SELECT id FROM zones WHERE code='WCR'), 'Superfast Express', 22, 'NZM', 'BSB'),
(22182, 'Bhopal Express', (SELECT id FROM zones WHERE code='WCR'), 'Superfast Express', 22, 'BPL', 'NDLS'),
(12150, 'Pushpak Express', (SELECT id FROM zones WHERE code='WCR'), 'Superfast Express', 22, 'BPL', 'CSMT'),
(12112, 'Vidarbha Express', (SELECT id FROM zones WHERE code='WCR'), 'Superfast Express', 22, 'CSMT', 'NGP'),
(18215, 'Durg–Nagpur Express', (SELECT id FROM zones WHERE code='SECR'), 'Express', 22, 'R', 'NGP'),
(12854, 'Amarkantak Express', (SELECT id FROM zones WHERE code='SECR'), 'Superfast Express', 22, 'HWH', 'BSP'),
(22811, 'Mumbai–Howrah Duronto', (SELECT id FROM zones WHERE code='SECR'), 'Duronto Express', 20, 'CSMT', 'HWH'),
(18030, 'Shalimar Express', (SELECT id FROM zones WHERE code='SECR'), 'Superfast Express', 22, 'BSP', 'CSMT'),
(18235, 'Bilaspur Express', (SELECT id FROM zones WHERE code='SECR'), 'Express', 22, 'BSP', 'NDLS'),
(12442, 'Bilaspur Rajdhani', (SELECT id FROM zones WHERE code='SECR'), 'Rajdhani Express', 20, 'NDLS', 'BSP'),
(18238, 'Chhattisgarh Express', (SELECT id FROM zones WHERE code='SECR'), 'Superfast Express', 24, 'NDLS', 'R'),
(20813, 'Raipur Rajdhani Express', (SELECT id FROM zones WHERE code='SECR'), 'Rajdhani Express', 20, 'NDLS', 'R'),
(18509, 'Visakhapatnam Express', (SELECT id FROM zones WHERE code='SECR'), 'Express', 22, 'VSKP', 'BSP'),
(12859, 'Gitanjali Express', (SELECT id FROM zones WHERE code='SECR'), 'Superfast Express', 24, 'HWH', 'CSMT'),
(10103, 'Mandovi Express', (SELECT id FROM zones WHERE code='KR'), 'Express', 22, 'CSMT', 'MAO'),
(10111, 'Konkan Kanya Express', (SELECT id FROM zones WHERE code='KR'), 'Express', 22, 'CSMT', 'MNG'),
(12133, 'Mumbai–Mangaluru Express', (SELECT id FROM zones WHERE code='KR'), 'Superfast Express', 22, 'CSMT', 'MNG'),
(12218, 'Kerala Sampark Kranti (KR)', (SELECT id FROM zones WHERE code='KR'), 'Superfast Express', 22, 'NDLS', 'ERS'),
(16345, 'Netravati Express', (SELECT id FROM zones WHERE code='KR'), 'Express', 22, 'CSMT', 'TVC'),
(12619, 'Matsyagandha Express', (SELECT id FROM zones WHERE code='KR'), 'Express', 22, 'CSMT', 'MNG'),
(22113, 'Kochuveli–LTT Tejas', (SELECT id FROM zones WHERE code='KR'), 'Tejas Express', 12, 'TVC', 'CSMT'),
(12051, 'Janshatabdi Dadar–Madgaon', (SELECT id FROM zones WHERE code='KR'), 'Jan Shatabdi Express', 12, 'DD', 'MAO'),
(16339, 'Mumbai–Nagercoil Express', (SELECT id FROM zones WHERE code='KR'), 'Express', 24, 'CSMT', 'TEN'),
(22907, 'Hapa–Bikaner Superfast', (SELECT id FROM zones WHERE code='KR'), 'Superfast Express', 22, 'MAO', 'MNG');


-- ── EXTRA: VANDE BHARAT FLEET ──────────────────────────────────────────
INSERT INTO trains (train_no, name, zone_id, train_type, total_coaches, origin_code, destination_code) VALUES
(22436, 'New Delhi–Varanasi Vande Bharat', (SELECT id FROM zones WHERE code='NR'), 'Vande Bharat Express', 16, 'NDLS', 'BSB'),
(22439, 'New Delhi–Katra Vande Bharat', (SELECT id FROM zones WHERE code='NR'), 'Vande Bharat Express', 16, 'NDLS', 'SVDK'),
(20901, 'Mumbai–Gandhinagar Vande Bharat', (SELECT id FROM zones WHERE code='WR'), 'Vande Bharat Express', 16, 'BCT', 'GNC'),
(20607, 'Chennai–Mysuru Vande Bharat', (SELECT id FROM zones WHERE code='SR'), 'Vande Bharat Express', 16, 'MAS', 'MYS'),
(20701, 'Secunderabad–Visakhapatnam Vande Bharat', (SELECT id FROM zones WHERE code='SCR'), 'Vande Bharat Express', 16, 'SC', 'VSKP'),
(22223, 'Mumbai–Shirdi Vande Bharat', (SELECT id FROM zones WHERE code='CR'), 'Vande Bharat Express', 16, 'CSMT', 'SNSI'),
(22225, 'Mumbai–Solapur Vande Bharat', (SELECT id FROM zones WHERE code='CR'), 'Vande Bharat Express', 16, 'CSMT', 'SUR'),
(20825, 'Bilaspur–Nagpur Vande Bharat', (SELECT id FROM zones WHERE code='SECR'), 'Vande Bharat Express', 16, 'BSP', 'NGP'),
(20833, 'Secunderabad–Tirupati Vande Bharat', (SELECT id FROM zones WHERE code='SCR'), 'Vande Bharat Express', 16, 'SC', 'TPTY'),
(20643, 'Chennai–Coimbatore Vande Bharat', (SELECT id FROM zones WHERE code='SR'), 'Vande Bharat Express', 8, 'MAS', 'CBE'),
(20171, 'Rani Kamlapati–Nizamuddin Vande Bharat', (SELECT id FROM zones WHERE code='WCR'), 'Vande Bharat Express', 16, 'RKMP', 'NZM'),
(22301, 'Howrah–New Jalpaiguri Vande Bharat', (SELECT id FROM zones WHERE code='ER'), 'Vande Bharat Express', 16, 'HWH', 'NJP'),
(20897, 'Howrah–Puri Vande Bharat', (SELECT id FROM zones WHERE code='SER'), 'Vande Bharat Express', 16, 'HWH', 'PURI'),
(22349, 'Patna–Howrah Vande Bharat', (SELECT id FROM zones WHERE code='ECR'), 'Vande Bharat Express', 8, 'PNBE', 'HWH'),
(20677, 'Vijayawada–Chennai Vande Bharat', (SELECT id FROM zones WHERE code='SCR'), 'Vande Bharat Express', 8, 'BZA', 'MAS');


-- ── 4. TRACKS ───────────────────────────────────────────────
INSERT INTO tracks (station_from_id, station_to_id, distance_km, line_type, electrified) VALUES
((SELECT id FROM stations WHERE code='NDLS'), (SELECT id FROM stations WHERE code='AGC'), 195, 'Double Line', 1),
((SELECT id FROM stations WHERE code='AGC'), (SELECT id FROM stations WHERE code='MTC'), 58, 'Double Line', 1),
((SELECT id FROM stations WHERE code='NDLS'), (SELECT id FROM stations WHERE code='CNB'), 440, 'Double Line', 1),
((SELECT id FROM stations WHERE code='CNB'), (SELECT id FROM stations WHERE code='LKO'), 80, 'Double Line', 1),
((SELECT id FROM stations WHERE code='LKO'), (SELECT id FROM stations WHERE code='GKP'), 272, 'Double Line', 1),
((SELECT id FROM stations WHERE code='NDLS'), (SELECT id FROM stations WHERE code='UMB'), 375, 'Double Line', 1),
((SELECT id FROM stations WHERE code='UMB'), (SELECT id FROM stations WHERE code='LDH'), 83, 'Double Line', 1),
((SELECT id FROM stations WHERE code='LDH'), (SELECT id FROM stations WHERE code='ASR'), 75, 'Double Line', 1),
((SELECT id FROM stations WHERE code='NDLS'), (SELECT id FROM stations WHERE code='CDG'), 256, 'Double Line', 1),
((SELECT id FROM stations WHERE code='NDLS'), (SELECT id FROM stations WHERE code='HW'), 313, 'Double Line', 1),
((SELECT id FROM stations WHERE code='HW'), (SELECT id FROM stations WHERE code='DDN'), 54, 'Single Line', 1),
((SELECT id FROM stations WHERE code='BCT'), (SELECT id FROM stations WHERE code='BRC'), 392, 'Double Line', 1),
((SELECT id FROM stations WHERE code='BRC'), (SELECT id FROM stations WHERE code='ADI'), 112, 'Double Line', 1),
((SELECT id FROM stations WHERE code='ADI'), (SELECT id FROM stations WHERE code='AII'), 272, 'Double Line', 1),
((SELECT id FROM stations WHERE code='AII'), (SELECT id FROM stations WHERE code='JP'), 132, 'Double Line', 1),
((SELECT id FROM stations WHERE code='JP'), (SELECT id FROM stations WHERE code='KOTA'), 261, 'Double Line', 1),
((SELECT id FROM stations WHERE code='KOTA'), (SELECT id FROM stations WHERE code='AGC'), 283, 'Double Line', 1),
((SELECT id FROM stations WHERE code='BCT'), (SELECT id FROM stations WHERE code='ST'), 263, 'Double Line', 1),
((SELECT id FROM stations WHERE code='ST'), (SELECT id FROM stations WHERE code='BRC'), 121, 'Double Line', 1),
((SELECT id FROM stations WHERE code='CSMT'), (SELECT id FROM stations WHERE code='PUNE'), 192, 'Double Line', 1),
((SELECT id FROM stations WHERE code='PUNE'), (SELECT id FROM stations WHERE code='SUR'), 249, 'Double Line', 1),
((SELECT id FROM stations WHERE code='SUR'), (SELECT id FROM stations WHERE code='SC'), 270, 'Double Line', 1),
((SELECT id FROM stations WHERE code='CSMT'), (SELECT id FROM stations WHERE code='NGP'), 1052, 'Double Line', 1),
((SELECT id FROM stations WHERE code='NGP'), (SELECT id FROM stations WHERE code='BSP'), 361, 'Double Line', 1),
((SELECT id FROM stations WHERE code='MAS'), (SELECT id FROM stations WHERE code='CBE'), 497, 'Double Line', 1),
((SELECT id FROM stations WHERE code='MAS'), (SELECT id FROM stations WHERE code='MDU'), 502, 'Double Line', 1),
((SELECT id FROM stations WHERE code='MAS'), (SELECT id FROM stations WHERE code='TVC'), 919, 'Double Line', 1),
((SELECT id FROM stations WHERE code='CBE'), (SELECT id FROM stations WHERE code='ERS'), 190, 'Double Line', 1),
((SELECT id FROM stations WHERE code='ERS'), (SELECT id FROM stations WHERE code='TVC'), 221, 'Double Line', 1),
((SELECT id FROM stations WHERE code='SC'), (SELECT id FROM stations WHERE code='HYB'), 12, 'Double Line', 1),
((SELECT id FROM stations WHERE code='HYB'), (SELECT id FROM stations WHERE code='BZA'), 437, 'Double Line', 1),
((SELECT id FROM stations WHERE code='BZA'), (SELECT id FROM stations WHERE code='MAS'), 430, 'Double Line', 1),
((SELECT id FROM stations WHERE code='SC'), (SELECT id FROM stations WHERE code='TPTY'), 614, 'Double Line', 1),
((SELECT id FROM stations WHERE code='VSKP'), (SELECT id FROM stations WHERE code='BZA'), 350, 'Double Line', 1),
((SELECT id FROM stations WHERE code='HWH'), (SELECT id FROM stations WHERE code='PNBE'), 544, 'Double Line', 1),
((SELECT id FROM stations WHERE code='PNBE'), (SELECT id FROM stations WHERE code='DDU'), 249, 'Double Line', 1),
((SELECT id FROM stations WHERE code='DDU'), (SELECT id FROM stations WHERE code='CNB'), 292, 'Double Line', 1),
((SELECT id FROM stations WHERE code='HWH'), (SELECT id FROM stations WHERE code='ASN'), 219, 'Double Line', 1),
((SELECT id FROM stations WHERE code='ASN'), (SELECT id FROM stations WHERE code='DHN'), 48, 'Double Line', 1),
((SELECT id FROM stations WHERE code='HWH'), (SELECT id FROM stations WHERE code='NJP'), 583, 'Double Line', 1),
((SELECT id FROM stations WHERE code='NJP'), (SELECT id FROM stations WHERE code='GHY'), 440, 'Single Line', 0),
((SELECT id FROM stations WHERE code='GHY'), (SELECT id FROM stations WHERE code='DBRG'), 439, 'Single Line', 0),
((SELECT id FROM stations WHERE code='SBC'), (SELECT id FROM stations WHERE code='MAS'), 362, 'Double Line', 1),
((SELECT id FROM stations WHERE code='SBC'), (SELECT id FROM stations WHERE code='MYS'), 139, 'Double Line', 1),
((SELECT id FROM stations WHERE code='SBC'), (SELECT id FROM stations WHERE code='UBL'), 421, 'Double Line', 0),
((SELECT id FROM stations WHERE code='HWH'), (SELECT id FROM stations WHERE code='KGP'), 120, 'Multiple Line', 1),
((SELECT id FROM stations WHERE code='KGP'), (SELECT id FROM stations WHERE code='BBS'), 464, 'Double Line', 1),
((SELECT id FROM stations WHERE code='BBS'), (SELECT id FROM stations WHERE code='PURI'), 60, 'Double Line', 1),
((SELECT id FROM stations WHERE code='CSMT'), (SELECT id FROM stations WHERE code='MAO'), 754, 'Single Line', 1),
((SELECT id FROM stations WHERE code='MAO'), (SELECT id FROM stations WHERE code='MNG'), 382, 'Single Line', 1),
((SELECT id FROM stations WHERE code='MNG'), (SELECT id FROM stations WHERE code='ERS'), 250, 'Double Line', 1),
((SELECT id FROM stations WHERE code='JP'), (SELECT id FROM stations WHERE code='BKN'), 328, 'Single Line', 0),
((SELECT id FROM stations WHERE code='JP'), (SELECT id FROM stations WHERE code='UDZ'), 664, 'Single Line', 0),
((SELECT id FROM stations WHERE code='JP'), (SELECT id FROM stations WHERE code='JU2'), 320, 'Single Line', 0);

-- ── 5. SCHEDULES ────────────────────────────────────────────
-- 12301 Howrah Rajdhani
INSERT INTO schedule (train_id, station_id, sequence_no, arrival_time, departure_time, day_no, halt_minutes) VALUES
((SELECT id FROM trains WHERE train_no=12301), (SELECT id FROM stations WHERE code='NDLS'), 1, '17:00', '17:00', 1, 0),
((SELECT id FROM trains WHERE train_no=12301), (SELECT id FROM stations WHERE code='CNB'), 2, '22:10', '22:20', 1, 10),
((SELECT id FROM trains WHERE train_no=12301), (SELECT id FROM stations WHERE code='ALD'), 3, '00:30', '00:45', 2, 15),
((SELECT id FROM trains WHERE train_no=12301), (SELECT id FROM stations WHERE code='DDU'), 4, '02:47', '03:02', 2, 15),
((SELECT id FROM trains WHERE train_no=12301), (SELECT id FROM stations WHERE code='GAYA'), 5, '05:45', '05:55', 2, 10),
((SELECT id FROM trains WHERE train_no=12301), (SELECT id FROM stations WHERE code='PNBE'), 6, '07:55', '08:05', 2, 10),
((SELECT id FROM trains WHERE train_no=12301), (SELECT id FROM stations WHERE code='ASN'), 7, '11:20', '11:25', 2, 5),
((SELECT id FROM trains WHERE train_no=12301), (SELECT id FROM stations WHERE code='HWH'), 8, '14:05', '14:05', 2, 0);

-- 12951 Mumbai Rajdhani
INSERT INTO schedule (train_id, station_id, sequence_no, arrival_time, departure_time, day_no, halt_minutes) VALUES
((SELECT id FROM trains WHERE train_no=12951), (SELECT id FROM stations WHERE code='NDLS'), 1, '16:25', '16:25', 1, 0),
((SELECT id FROM trains WHERE train_no=12951), (SELECT id FROM stations WHERE code='KOTA'), 2, '21:38', '21:43', 1, 5),
((SELECT id FROM trains WHERE train_no=12951), (SELECT id FROM stations WHERE code='RTM'), 3, '00:08', '00:13', 2, 5),
((SELECT id FROM trains WHERE train_no=12951), (SELECT id FROM stations WHERE code='BRC'), 4, '03:53', '03:58', 2, 5),
((SELECT id FROM trains WHERE train_no=12951), (SELECT id FROM stations WHERE code='ST'), 5, '05:50', '05:52', 2, 2),
((SELECT id FROM trains WHERE train_no=12951), (SELECT id FROM stations WHERE code='BCT'), 6, '08:35', '08:35', 2, 0);

-- 12611 Chennai Rajdhani
INSERT INTO schedule (train_id, station_id, sequence_no, arrival_time, departure_time, day_no, halt_minutes) VALUES
((SELECT id FROM trains WHERE train_no=12611), (SELECT id FROM stations WHERE code='NZM'), 1, '15:55', '15:55', 1, 0),
((SELECT id FROM trains WHERE train_no=12611), (SELECT id FROM stations WHERE code='GWL'), 2, '19:10', '19:15', 1, 5),
((SELECT id FROM trains WHERE train_no=12611), (SELECT id FROM stations WHERE code='BPL'), 3, '22:30', '22:35', 1, 5),
((SELECT id FROM trains WHERE train_no=12611), (SELECT id FROM stations WHERE code='NGP'), 4, '03:35', '03:40', 2, 5),
((SELECT id FROM trains WHERE train_no=12611), (SELECT id FROM stations WHERE code='SC'), 5, '10:35', '10:40', 2, 5),
((SELECT id FROM trains WHERE train_no=12611), (SELECT id FROM stations WHERE code='MAS'), 6, '15:45', '15:45', 2, 0);

-- 12841 Coromandel Express
INSERT INTO schedule (train_id, station_id, sequence_no, arrival_time, departure_time, day_no, halt_minutes) VALUES
((SELECT id FROM trains WHERE train_no=12841), (SELECT id FROM stations WHERE code='HWH'), 1, '14:05', '14:05', 1, 0),
((SELECT id FROM trains WHERE train_no=12841), (SELECT id FROM stations WHERE code='KGP'), 2, '15:45', '15:47', 1, 2),
((SELECT id FROM trains WHERE train_no=12841), (SELECT id FROM stations WHERE code='BBS'), 3, '20:35', '20:45', 1, 10),
((SELECT id FROM trains WHERE train_no=12841), (SELECT id FROM stations WHERE code='VSKP'), 4, '05:00', '05:10', 2, 10),
((SELECT id FROM trains WHERE train_no=12841), (SELECT id FROM stations WHERE code='BZA'), 5, '09:05', '09:10', 2, 5),
((SELECT id FROM trains WHERE train_no=12841), (SELECT id FROM stations WHERE code='MAS'), 6, '14:30', '14:30', 2, 0);

-- 12627 Karnataka Express
INSERT INTO schedule (train_id, station_id, sequence_no, arrival_time, departure_time, day_no, halt_minutes) VALUES
((SELECT id FROM trains WHERE train_no=12627), (SELECT id FROM stations WHERE code='SBC'), 1, '20:15', '20:15', 1, 0),
((SELECT id FROM trains WHERE train_no=12627), (SELECT id FROM stations WHERE code='MYS'), 2, '21:50', '22:00', 1, 10),
((SELECT id FROM trains WHERE train_no=12627), (SELECT id FROM stations WHERE code='UBL'), 3, '02:30', '02:40', 2, 10),
((SELECT id FROM trains WHERE train_no=12627), (SELECT id FROM stations WHERE code='SC'), 4, '09:10', '09:20', 2, 10),
((SELECT id FROM trains WHERE train_no=12627), (SELECT id FROM stations WHERE code='NGP'), 5, '17:20', '17:30', 2, 10),
((SELECT id FROM trains WHERE train_no=12627), (SELECT id FROM stations WHERE code='BPL'), 6, '22:30', '22:40', 2, 10),
((SELECT id FROM trains WHERE train_no=12627), (SELECT id FROM stations WHERE code='AGC'), 7, '04:50', '04:55', 3, 5),
((SELECT id FROM trains WHERE train_no=12627), (SELECT id FROM stations WHERE code='NDLS'), 8, '07:35', '07:35', 3, 0);